title: Varendra Saith
logo: /assets/cropped_image.png
description: Hi, I'm Varendra, and I'm an aspiring software developer, recently graduated from the University of Dundee with a MSc Computer Science (Distinction). I'm currently interested in learning graphics programming and full stack web development. 
show_downloads: false
theme: jekyll-theme-minimal

site.url: https://www.linkedin.com/in/varendrasaith
