title: Varendra Saith
logo: /assets/file.png
description: Hi, I'm Varendra and I love to learn new things. Previously worked in the energy sector as a geophysicist, and now I'm having a blast learning the ins and outs of software development.
show_downloads: false
theme: jekyll-theme-minimal

linkedin_username: varendrasaith
