title: Varendra Saith
logo: /assets/cropped_image.png
description: Hi, I'm Varendra, a soon to be Msc graduate of Computer Science at the University of Dundee. I'm currently focusing on software and game development, and am currently challenging myself to build a game engine from the ground up. I also used to be a geophysicist, with 5+ years experience in the energy industry.
show_downloads: false
theme: jekyll-theme-minimal

site.url: https://www.linkedin.com/in/varendrasaith
